### ISSUE TITLE
Landing page tags routing error

### ISSUE THREAD

**Issue by patrickhaede** [digitallawyer/legaltechlist#16]

**Comment by paulblizzard** [comment]
Hi Patrick, 

This is being caused by this commit:  https://github.com/digitallawyer/legaltechlist/commit/25d10536420c59fbda8e3e8faf059578c598ccfc

Paul

**Comment by patrickhaede** [comment]
@paulblizzard Hi Paul, yes, this is true. I will fix it tonight.
