### ISSUE TITLE
Styling of Category boxes on front page

### ISSUE THREAD

**Issue by paulblizzard** [digitallawyer/legaltechlist#47]
The styling of Categories on the front page needs some TLC.  There was a new category added that needs styling, and it would be nice to have a more flexible solution (maybe repeat the colour pattern).

Steps to Reproduce:

* navigate to http://techindex.law.stanford.edu/
* see 'Compliance' category box
* *outcome* no styles

**Comment by paulblizzard** [comment]
@patrickhaede

**Comment by digitallawyer** [comment]
Resolved
