### ISSUE TITLE
Adding another company to the list

### ISSUE THREAD

**Issue by Trbb2411** [digitallawyer/legaltechlist#6]
Similar to the other user, I wasn't sure of the best way to contribute to the list, so I'd like to submit a suggestion:

[Milyli](http://milyli.com) is an e-discovery software company specializing in [automated redaction](http://milyi.com/blackout), reporting, and managed services for kCura's Relativity platform.

**Comment by patrickhaede** [comment]
@Trbb2411 Hi, you can submit a new company right on our site: http://tech.law.stanford.edu/companies/new
